<!doctype html>

<html>

  <head>
    <title>List of News</title>
    <meta charset="utf-8" />
	<link rel="stylesheet" href="./style.css" />
	
  </head>
  <body>
  <H1> List of News</H1>
  
<?php

require 'News.php';

try{
	// connect to database 
	//TODO: check for connect with text file
	$db = new PDO('mysql:host=localhost;dbname=news_form','root','');
}catch(Exception $e){
	die('Erreur :' . $e->getMessage());
}

//prepare request for data
$request = $db->query('SELECT id, header, author, text FROM News');

?>
	<table class="newsList">
		<tbody >
		
<?php
//get data in array
while ($data = $request->fetch(PDO::FETCH_ASSOC)) 
{
  //create an object news with data
  $news = new News;
  //add data to news object
  $news->hydrate($data);
  
  echo $news->getHTML();
  
}
?>
	</tbody>
	</table>

<!-- allow user to return to form.html -->
	<br/>
	<a href="./form.html" >return to form</a>

	<script type="text/javascript" src="./js/jquery-2.0.3.min.js"></script>
	<script type="text/javascript" src="./js/newsclick.js"></script>
	
  </body>

</html>

