<?php

require 'News.php';

try{
	// connect to database 
	//TODO: check for connect with text file
	$db = new PDO('mysql:host=localhost;dbname=news_form','root','');
}catch(Exception $e){
	die('Erreur :' . $e->getMessage());
}


$request = $db->query('SELECT id, header, author, text FROM News');

?>
	<table>
		<tbody>
<?php
//get data in array
while ($data = $request->fetch(PDO::FETCH_ASSOC)) 
{
  //create an object news with data
  $news = new News;
  $news->hydrate($data);
  
  echo $news->getHTML();
  
  
}
?>
	</tbody>
	</table>




